use regex::Regex;
use std::net::IpAddr;
use std::str::FromStr;
use ipnet::IpNet;

// Use the proto structures generated by tonic
pub mod protocol {
    tonic::include_proto!("protocol");
}

use protocol::{Connection, Operator, Rule};

pub fn match_rule(rule: &Rule, connection: &Connection) -> bool {
    if !rule.enabled {
        return false;
    }
    
    if let Some(operator) = &rule.operator {
        return match_operator(operator, connection);
    }
    
    false
}

fn match_operator(op: &Operator, conn: &Connection) -> bool {
    match op.r#type.as_str() {
        "simple" => match_simple(op, conn),
        "regexp" => match_regexp(op, conn),
        "network" => match_network(op, conn),
        "range" => match_range(op, conn),
        "list" => match_list(op, conn),
        _ => {
            eprintln!("Warning: Unknown operator type: {}", op.r#type);
            false
        }
    }
}

fn match_simple(op: &Operator, conn: &Connection) -> bool {
    let value = get_operand_value(&op.operand, conn);
    if op.sensitive {
        value == op.data
    } else {
        value.to_lowercase() == op.data.to_lowercase()
    }
}

fn match_regexp(op: &Operator, conn: &Connection) -> bool {
    let value = get_operand_value(&op.operand, conn);
    let pattern = if op.sensitive {
        op.data.clone()
    } else {
        format!("(?i){}", op.data)
    };

    if let Ok(re) = Regex::new(&pattern) {
        re.is_match(&value)
    } else {
        false
    }
}

fn match_network(op: &Operator, conn: &Connection) -> bool {
    let ip_str = if op.operand == "dest.ip" || op.operand == "dest.network" {
        &conn.dst_ip
    } else {
        &conn.src_ip
    };

    if let (Ok(ip), Ok(net)) = (IpAddr::from_str(ip_str), IpNet::from_str(&op.data)) {
        net.contains(&ip)
    } else {
        false
    }
}

fn match_range(op: &Operator, conn: &Connection) -> bool {
    let value_str = get_operand_value(&op.operand, conn);
    if let Ok(val) = value_str.parse::<u64>() {
        let parts: Vec<&str> = op.data.split('-').collect();
        if parts.len() == 2 {
            if let (Ok(min), Ok(max)) = (parts[0].trim().parse::<u64>(), parts[1].trim().parse::<u64>()) {
                return val >= min && val <= max;
            }
        }
    }
    false
}

fn match_list(op: &Operator, conn: &Connection) -> bool {
    // List logic: usually AND matching for nested operators
    for nested_op in &op.list {
        if !match_operator(nested_op, conn) {
            return false;
        }
    }
    true
}

fn get_operand_value(operand: &str, conn: &Connection) -> String {
    match operand {
        "process.path" => conn.process_path.clone(),
        "process.id" => conn.process_id.to_string(),
        "dest.ip" => conn.dst_ip.clone(),
        "dest.host" => conn.dst_host.clone(),
        "dest.port" => conn.dst_port.to_string(),
        "source.ip" => conn.src_ip.clone(),
        "source.port" => conn.src_port.to_string(),
        "user.id" => conn.user_id.to_string(),
        "protocol" => conn.protocol.clone(),
        "process.hash.sha256" => conn.process_checksums.get("sha256").cloned().unwrap_or_default(),
        "process.parent.path" => conn.process_tree.first().map(|ti| ti.key.clone()).unwrap_or_default(),
        _ => String::new(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_hash_match() {
        let mut checksums = std::collections::HashMap::new();
        checksums.insert("sha256".to_string(), "abc123def".to_string());
        
        let conn = Connection {
            process_checksums: checksums,
            ..Default::default()
        };
        let op = Operator {
            r#type: "simple".to_string(),
            operand: "process.hash.sha256".to_string(),
            data: "abc123def".to_string(),
            ..Default::default()
        };
        assert!(match_simple(&op, &conn));
    }

    #[test]
    fn test_parent_path_match() {
        use protocol::StringInt;
        let conn = Connection {
            process_tree: vec![StringInt { key: "/usr/bin/bash".to_string(), ..Default::default() }],
            ..Default::default()
        };
        let op = Operator {
            r#type: "simple".to_string(),
            operand: "process.parent.path".to_string(),
            data: "/usr/bin/bash".to_string(),
            ..Default::default()
        };
        assert!(match_simple(&op, &conn));
    }
}